# This workflow updates the channels.csv file to the latest stats and eventually posts an update on Twitter

name: Check updated stats

on:
  schedule:
   - cron: "*/5 * * * *" # Runs every five minutes, everyday (actual timing may vary, depending on GitHub)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content # Checkout the repository content to GitHub runner
      uses: actions/checkout@v2
    - name: setup python # Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # The script actually runs fine with Python 3.8 and 3.9
    - name: install pip # Install pip
      run: |
        python -m pip install --upgrade pip
    - name: execute py script # Run the script to fetch the latest data
      run: |
        python main.py
      env: # API KEYs are passed as environment variables. For more info https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }} 
    - name: Commit changes # Commit changes to the master branch (if the message.txt file is not empty)
      run: |
        git config --global user.name 'marco97pa'
        git config --global user.email 'marco97pa@live.it'
        test -f message.txt && (echo -e 'Channels stats update\n' | cat - message.txt > temp && mv temp message.txt) || echo
        test -f message.txt && (cat message.txt) || echo
        test -f message.txt && (git add .) || echo
        test -f message.txt && (git commit -F message.txt) || echo
        test -f message.txt && (git push) || echo
        test -f message.txt && (rm message.txt) || echo No changes to commit
