# This workflow posts a weekly report and updates the channels.csv file to the latest stats

name: Weekly report

on:
  schedule:
   - cron: "0 18 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    - name: pip install tweepy
      run: |
        python -m pip install --upgrade pip
        pip install tweepy
    - name: execute py script # run the run.py to get the latest data
      run: |
        python main.py -report
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }} # if run.py requires passwords..etc, set it as secrets
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_KEY: ${{ secrets.TWITTER_ACCESS_KEY }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
    - name: Commit changes
      run: |
        git config --global user.name 'marco97pa'
        git config --global user.email 'marco97pa@live.it'
        test -f message.txt && (echo -e 'Channels stats update\n' | cat - message.txt > temp && mv temp message.txt) || echo
        test -f message.txt && (cat message.txt) || echo
        test -f message.txt && (git add .) || echo
        test -f message.txt && (git commit -F message.txt) || echo
        test -f message.txt && (git push) || echo
        test -f message.txt && (rm message.txt) || echo No changes to commit
